name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Compile Java project
      run: javac src/main/java/com/mycompany/addressbook/*.java

    - name: Run basic test
      run: echo "Compilación completada correctamente"
